
# make "all" the target.
all:


# Disable linking math libs because  not needed here.  Just for compilation speed.
# no, it's now needed for context-fst-test.
# MATHLIB = NONE

EXTRA_CXXFLAGS = -Wno-sign-compare

include ../../kaldi.mk


ifeq ($(KALDI_FLAVOR),static)
  $(error You cannot build the pybind directory unless the build was dynamic; reconfigure with --shared option.)
endif

PYBIND_INCLUDES=$(shell python3 -m pybind11 --includes)

CXXFLAGS += $(PYBIND_INCLUDES)

PYBIND_EXTENSION=$(shell python3-config --extension-suffix)
LIBFILE=kaldi-pybind
LIBFILE_EXTENSION=$(PYBIND_EXTENSION)

# pybind11 is heavily templated and generates code that is bloated before optimization.
# -flto is link time optimization which apparently is important.
CXXFLAGS += -O3 -flto -I. -I../..
LDFLAGS += -flto
# TODO:

ifeq ($(shell uname),Darwin)
  LDFLAGS += -undefined dynamic_lookup
endif

CCFILES = hmm_pybind.cc \
          tree-accu_pybind.cc

LIBNAME = kaldi_hmm_pybind


ADDLIBS = ../../util/kaldi-util.a ../../matrix/kaldi-matrix.a ../../hmm/kaldi-hmm.a ../../base/kaldi-base.a

ifeq ($(shell uname), Darwin)
EXTRA_LDLIBS += $(foreach dep,$(ADDLIBS), ../../lib/lib$(notdir $(basename $(dep))).dylib)
else
EXTRA_LDLIBS += $(foreach dep,$(ADDLIBS), $(dir $(dep))lib$(notdir $(basename $(dep))).so)
endif

LIBFILE=$(LIBNAME)$(LIBFILE_EXTENSION)

.PHONY: all clean test

all: $(LIBFILE)

$(LIBFILE): $(ADDLIBS) $(CCFILES)
  ifeq ($(shell uname), Darwin)
	$(CXX) $(CXXFLAGS)   -o $@  $(LDFLAGS) $(CCFILES) $(OBJFILES) $(LDLIBS)
	install_name_tool -add_rpath ../../lib $(LIBFILE)
  else ifeq ($(shell uname), Linux)
        # Building shared library from static (static was compiled with -fPIC)
	$(CXX) $(CXXFLAGS) -shared -o $@ $(CCFILES) -Wl,--no-whole-archive -Wl,-rpath=$(CURDIR)/../../lib $(LDFLAGS) $(LDLIBS) $(EXTRA_LDLIBS)
  else  # Platform not supported
	$(error Dynamic libraries not supported on this platform. Run configure with --static flag.)
  endif
	python3 -c 'import kaldi_hmm_pybind'  # this line is a test.

clean:
	-rm -f *.so
	-rm -rf __pycache__
	-rm -rf *$(LIBFILE_EXTENSION).dSYM

test: all
	python3 tests/test_kaldi_pybind.py
	python3 tests/test_matrix.py

# valgrind-python.supp is from http://svn.python.org/projects/python/trunk/Misc/valgrind-python.supp
# since we do not compile Python from souce, we follow the comment in valgrind-python.supp
# to uncomment suppressions for PyObject_Free and PyObject_Realloc.
valgrind:
	valgrind --tool=memcheck --suppressions=./valgrind-python.supp \
   python3 -E -tt ./tests/test_matrix.py
